/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_apk;

import com.formdev.flatlaf.intellijthemes.FlatGradiantoMidnightBlueIJTheme;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MabidPC
 */
public class HomePage extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String user, pass;
    /**
     * Creates new form HomePage
     */
    public HomePage(String u, String p) {
        try{
            initComponents();
            con = DBconnection.connectionDB();
            user = u;
            pass = p;
            String sql = "SELECT * FROM login WHERE username = ? AND password = ?; ";
                pst = con.prepareStatement(sql);
                pst.setString(1, user);
                pst.setString(2, pass);
                rs = pst.executeQuery();
                
                if(rs.next()){
                    String nama = rs.getString("nama");
                    //JOptionPane.showMessageDialog(null, "berhasil " + nama);
                    NameUser.setText(nama);
                    
                    
                } else{
                    JOptionPane.showMessageDialog(null, "error");
                }
        
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        } finally {
            try{
                rs.close();
                pst.close();
            }catch (Exception e){
                e.printStackTrace();
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ML = new javax.swing.JButton();
        btn_PUBG = new javax.swing.JButton();
        NameUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JLabel();
        btn_Home = new javax.swing.JLabel();
        btn_Back = new javax.swing.JLabel();
        HomePanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 715));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ML.setText("ML");
        btn_ML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MLActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ML, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 100, -1));

        btn_PUBG.setText("PUBG");
        btn_PUBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PUBGActionPerformed(evt);
            }
        });
        getContentPane().add(btn_PUBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 100, -1));

        NameUser.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        NameUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NameUser.setText("____ ");
        getContentPane().add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 300, 20));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Hello ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 50, 20));

        btn_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ExitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 30, 30));

        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 30, 30));

        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 30, 30));

        HomePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas_apk/gambar/Home Page.png"))); // NOI18N
        getContentPane().add(HomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_ExitMouseClicked

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Don't Action");
    }//GEN-LAST:event_btn_BackMouseClicked

    private void btn_MLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MLActionPerformed
        // TODO add your handling code here:
        new MlPage(user, pass).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_MLActionPerformed

    private void btn_PUBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PUBGActionPerformed
        // TODO add your handling code here:
        new PubgPage(user, pass).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_PUBGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            FlatGradiantoMidnightBlueIJTheme.setup();
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomePage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomePanel;
    private javax.swing.JLabel NameUser;
    private javax.swing.JLabel btn_Back;
    private javax.swing.JLabel btn_Exit;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JButton btn_ML;
    private javax.swing.JButton btn_PUBG;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel {

            private Color backgroundColor;
            private int cornerRadius = 15;

            public RoundedPanel(LayoutManager layout, int radius) {
                super(layout);
                cornerRadius = radius;
            }

            public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
                super(layout);
                cornerRadius = radius;
                backgroundColor = bgColor;
            }

            public RoundedPanel(int radius) {
                super();
                cornerRadius = radius;

            }

            public RoundedPanel(int radius, Color bgColor) {
                super();
                cornerRadius = radius;
                backgroundColor = bgColor;
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Dimension arcs = new Dimension(cornerRadius, cornerRadius);
                int width = getWidth();
                int height = getHeight();
                Graphics2D graphics = (Graphics2D) g;
                graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                //Draws the rounded panel with borders.
                if (backgroundColor != null) {
                    graphics.setColor(backgroundColor);
                } else {
                    graphics.setColor(getBackground());
                }
                graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
                graphics.setColor(getForeground());
    //            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
    //
            }
        }
}
