/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_apk;

import com.formdev.flatlaf.intellijthemes.FlatGradiantoMidnightBlueIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MabidPC
 */

public class MlPage extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String user, pass;
    /**
     * Creates new form MlPage
     */
    public MlPage(String u, String p) {
        try{
            initComponents();
            con = DBconnection.connectionDB();
            user = u;
            pass = p;
            String sql = "SELECT * FROM login WHERE username = ? AND password = ?; ";
                pst = con.prepareStatement(sql);
                pst.setString(1, user);
                pst.setString(2, pass);
                rs = pst.executeQuery();
                
                if(rs.next()){
                    String nama = rs.getString("nama");
                    //JOptionPane.showMessageDialog(null, "berhasil " + nama);
                    NameUser.setText(nama);
                    
                    
                } else{
                    JOptionPane.showMessageDialog(null, "error");
                }
        
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        } finally {
            try{
                rs.close();
                pst.close();
            }catch (Exception e){
                e.printStackTrace();
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Varian = new javax.swing.ButtonGroup();
        btn_pembayaran = new javax.swing.JButton();
        chck_172 = new javax.swing.JRadioButton();
        chck_343 = new javax.swing.JRadioButton();
        chck_86 = new javax.swing.JRadioButton();
        chck_429 = new javax.swing.JRadioButton();
        chck_257 = new javax.swing.JRadioButton();
        txt_warn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameUser = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JLabel();
        btn_Home = new javax.swing.JLabel();
        btn_Back = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_server = new javax.swing.JTextField();
        Backg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pembayaran.setText("Pembayaran");
        btn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 230, 40));

        Varian.add(chck_172);
        getContentPane().add(chck_172, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 20, -1));

        Varian.add(chck_343);
        getContentPane().add(chck_343, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 20, -1));

        Varian.add(chck_86);
        getContentPane().add(chck_86, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 20, -1));

        Varian.add(chck_429);
        getContentPane().add(chck_429, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 20, -1));

        Varian.add(chck_257);
        getContentPane().add(chck_257, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 20, -1));

        txt_warn.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(txt_warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 210, 20));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Hello ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 50, 20));

        NameUser.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        NameUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NameUser.setText("____ ");
        getContentPane().add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 300, 20));

        btn_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ExitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 30, 30));

        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 30, 30));

        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 30, 30));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 170, -1));
        getContentPane().add(txt_server, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 160, -1));

        Backg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas_apk/gambar/ML Page.png"))); // NOI18N
        getContentPane().add(Backg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembayaranActionPerformed
        // TODO add your handling code here:
        int cek = 0;
        if (getId().isEmpty() || getServer().isEmpty()){
            txt_warn.setText("Masukkan id Server Terlebih dahulu");
        } else {
            cek = cek + 1;
        }
        
        if (varian().isEmpty()){
            txt_warn.setText("Pilih Varian Diamond");
        } else {
            cek = cek + 1;
        }
        
        if (cek == 2){
            JOptionPane.showMessageDialog(null, getId() + " " + getServer() + " " + varian());
            new PembayaranPage(user, pass, 1).setVisible(true);
            inputSQL();
            this.dispose();
            
        }
        
        
        
    }//GEN-LAST:event_btn_pembayaranActionPerformed

    private void btn_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_ExitMouseClicked

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        // TODO add your handling code here:
        new HomePage(user, pass).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackMouseClicked

    public String getId(){
        String id = txt_id.getText();
        return id;
    }
    
    public String getServer(){
        String server = txt_server.getText();
        return server;
    }
    
        String dm = "";
        String harga = "";
        String  pilih = "";
    public String varian(){
            if (chck_86.isSelected()){
                dm = "Varian 86";
                harga = " dengan harga Rp. 20.000";
            } else if (chck_172.isSelected()){
                dm = "Varian 172";
                harga = " dengan harga Rp. 40.000";
            } else if (chck_257.isSelected()){
                dm = "Varian 257";
                harga = " dengan harga Rp. 60.000";
            } else if (chck_343.isSelected()){
                dm = "Varian 343";
                harga = " dengan harga Rp. 80.000";
            } else if (chck_429.isSelected()){
                dm = "Varian 429";
                harga = " dengan harga Rp. 100.000";
            } else {
                JOptionPane.showMessageDialog(null, "Pilih varian Diamond");
                

            }
        pilih = dm + harga;
        return pilih;
    }
    
    public void inputSQL(){
        try{
            
            String sql = "INSERT INTO Ml (username, user_Id, server_Id, varian, harga) VALUES (?,?,?,?,?);";
            pst = con.prepareStatement(sql);
            pst.setString(1, user);
            pst.setString(2, getId());
            pst.setString(3, getServer());
            pst.setString(4, dm);
            pst.setString(5, harga);
            if (pst.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "Input Berhasil");
                this.dispose();
            }
            
            
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Input Failed" + e);
        } finally {
            try{
                rs.close();
                pst.close();
            }catch (Exception e){
                e.printStackTrace();
            }
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MlPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MlPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MlPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MlPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            FlatGradiantoMidnightBlueIJTheme.setup();
        } catch (Exception e){
            e.printStackTrace();
        }
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MlPage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backg;
    private javax.swing.JLabel NameUser;
    private javax.swing.ButtonGroup Varian;
    private javax.swing.JLabel btn_Back;
    private javax.swing.JLabel btn_Exit;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JRadioButton chck_172;
    private javax.swing.JRadioButton chck_257;
    private javax.swing.JRadioButton chck_343;
    private javax.swing.JRadioButton chck_429;
    private javax.swing.JRadioButton chck_86;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_server;
    private javax.swing.JLabel txt_warn;
    // End of variables declaration//GEN-END:variables
}
